language: node_js

before_install:
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn=1.21.1-1

cache:
  yarn: true

install:
  - yarn --silent

script:
  - yarn run test
  - yarn run codecov -f coverage/*.json
  - yarn run lint

before_deploy:
  - pip install --user awscli
  - yarn run build

deploy:
  provider: script
  script: ~/.local/bin/aws s3 sync dist s3://beta.findeth.io --region=eu-west-1 --delete
  skip-cleanup: true
  on:
    branch: master

after_deploy:
  - aws configure set preview.cloudfront true
  - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
